package com.archiveos.ai.memory;
import com.archiveos.ai.decision.DecisionRepository; import com.archiveos.ai.obsidian.Json; import com.archiveos.ai.obsidian.ObsidianVaultResolver; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.security.*; import java.time.Instant; import java.util.*; import org.springframework.stereotype.Service;
@Service public class MemoryService { private final MemoryRepository records; private final DecisionRepository decisions; private final ObsidianVaultResolver vault;
 public MemoryService(MemoryRepository r,DecisionRepository d,ObsidianVaultResolver v){records=r;decisions=d;vault=v;}
 public Map<String,Object> draft(String recommendationId){Map<String,Object> existing=records.findBySource(recommendationId);if(existing!=null)return existing;Map<String,Object>d=decisions.find(recommendationId);if(d==null)throw new IllegalArgumentException("Decision recommendation not found.");if(!"APPROVED".equals(d.get("status")))throw new IllegalStateException("Only an approved decision can create a memory draft.");Object refs=d.get("references_json");if(!(refs instanceof List<?> l)||l.isEmpty())throw new IllegalStateException("Evidence is required before creating a memory draft.");String service=String.valueOf(d.getOrDefault("service","ArchiveOS"));Map<String,Object> draft=new LinkedHashMap<>();draft.put("title","Decision: "+service+" — "+limit(String.valueOf(d.get("summary")),90));draft.put("memoryType","Decision");draft.put("service",service);draft.put("correlationId",d.get("correlation_id"));draft.put("entityId",d.get("entity_id"));draft.put("observedAt",d.get("created_at"));draft.put("problem",d.get("question"));draft.put("evidence",d.get("observed_facts"));draft.put("references",refs);draft.put("decision",d.get("summary"));draft.put("approvedBy",d.get("decided_by"));draft.put("approvalReason",d.get("decision_reason"));draft.put("actions",d.get("recommended_actions"));draft.put("expectedOutcome","PENDING_OUTCOME");draft.put("actualOutcome","PENDING_OUTCOME");draft.put("lessonsLearned","Pending human outcome review.");draft.put("tags",List.of("archiveos","decision",safe(service)));draft.put("sensitivity","SYNTHETIC_OPERATIONAL");draft.put("sourceIds",List.of(recommendationId));Map<String,Object> input=new LinkedHashMap<>();input.put("memoryId","memory-"+UUID.randomUUID());input.put("sourceId",recommendationId);input.put("title",draft.get("title"));input.put("memoryType","Decision");input.put("service",service);input.put("correlationId",d.get("correlation_id"));input.put("entityId",d.get("entity_id"));input.put("draft",draft);return records.create(input);}
 public Map<String,Object> get(String id){return records.find(id);} public List<Map<String,Object>> list(){return records.list();} public Map<String,Object> approve(String id,String by,String reason){Map<String,Object> r=records.find(id);if(r==null)return null;if(!"DRAFT".equals(r.get("status")))throw new IllegalStateException("Only DRAFT memory can be approved.");return records.approve(id,by,limit(reason,500));}
 public Map<String,Object> write(String id){Map<String,Object> r=records.find(id);if(r==null)return null;if(!"APPROVED".equals(r.get("status")))throw new IllegalStateException("Only APPROVED memory can be written.");Map<String,Object> d=(Map<String,Object>)r.get("draft");String name=safe(String.valueOf(r.get("memory_id")))+".md";Path root=vault.resolveVaultPath().toAbsolutePath().normalize();Path target=root.resolve("Decisions").resolve(name).normalize();if(!target.startsWith(root))throw new IllegalStateException("Unsafe memory path.");try{Files.createDirectories(target.getParent());String markdown=markdown(d);Files.writeString(target,markdown,StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW);return records.written(id,"Decisions/"+name,sha(markdown));}catch(FileAlreadyExistsException e){return records.written(id,"Decisions/"+name,"");}catch(Exception e){throw new IllegalStateException("Memory write failed: "+e.getClass().getSimpleName());}}
 private String markdown(Map<String,Object>d){return "# "+d.get("title")+"\n\n> Human-approved synthetic operational memory.\n\n## Problem\n"+d.get("problem")+"\n\n## Observed facts\n"+Json.write(d.get("evidence"))+"\n\n## References\n"+Json.write(d.get("references"))+"\n\n## Decision\n"+d.get("decision")+"\n\n## Actions\n"+Json.write(d.get("actions"))+"\n\n## Outcome\nExpected: "+d.get("expectedOutcome")+"\nActual: "+d.get("actualOutcome")+"\n\n## Lessons learned\n"+d.get("lessonsLearned")+"\n";}
 private String safe(String v){return v==null?"archiveos":v.replaceAll("[^A-Za-z0-9_-]","-");}private String nullable(Object v){return v==null?null:String.valueOf(v);}private String limit(String v,int n){return v==null?"":v.length()>n?v.substring(0,n):v;}private String sha(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){return "";}}
}
